'use strict';

var FB_PAGE_TOKEN = 'EAAB5QFcrQtsBAIA3fcMnIlS04VsQEDxV2E4ktvsvpMLTLzC6S9jt1EWhZC43BBhZBq8eUNug1msyLABhcV0zyUFqSJTSpxeYAvjNS9OdJR4iDSNRB0PLvzn11xbSMPyVrv04hBx9CFQZAwEktGVbZCZAGlBZC5TcbXAdZCIHVK2NEqrWQXglDHp'

var FB_VERIFY_TOKEN = 'dbcorpFirstBot';

module.exports = {
  FB_PAGE_TOKEN,
  FB_VERIFY_TOKEN,
};
